# Generated by Django 3.2.6 on 2021-08-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='productimg/', verbose_name=''),
        ),
    ]
