# Generated by Django 3.2.5 on 2021-08-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('bank', models.CharField(choices=[('ICICI', 'ICICI'), ('SBI', 'SBI'), ('HDFC', 'HDFC'), ('BANK OF BARODA', 'BANK OF BARODA'), ('PUNJAB NATIONAL BANK', 'PUNJAB NATIONAL BANK'), ('CENTRAL BANK', 'CENTRAL BANK'), ('AXIS BANK', 'AXIS BANK')], max_length=200)),
                ('bank_account', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('working_hours', models.TimeField()),
                ('required_working_hours', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
