# Generated by Django 2.2.12 on 2021-08-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('bank', models.CharField(choices=[('ICICI', 'ICICI'), ('SBI', 'SBI'), ('HDFC', 'HDFC'), ('BANK OF BARODA', 'BANK OF BARODA'), ('PUNJAB NATIONAL BANK', 'PUNJAB NATIONAL BANK'), ('CENTRAL BANK', 'CENTRAL BANK'), ('AXIS BANK', 'AXIS BANK')], max_length=200)),
                ('bank_account', models.IntegerField()),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Daman & Diu', 'Daman & Diu'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('working_hours', models.TimeField()),
                ('required_working_hours', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
            ],
        ),
    ]
