# Generated by Django 3.2.6 on 2021-08-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_orderplaced_product'),
        ('Cart', '0002_auto_20210811_1242'),
        ('Partner', '0002_auto_20210805_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
