# Generated by Django 2.2.12 on 2021-07-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atttedance',
            new_name='Attendance',
        ),
    ]
