# Generated by Django 3.2.6 on 2021-08-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
